# Simulation parameters
NUM_VIRTUAL_MACHINES = 5
NUM_TASKS = 1000
SIMULATION_TIME = 300_000
SCHEDULING_INTERVAL = 1000 
RANDOM_SEED = 42
ENABLE_VISUALIZATION = True
METRIC_PATH = r"outputs\metrics.csv"

# Task parameters
TASK_LENGTH_RANGE = (500, 1000)
TASK_DEADLINE_RANGE = (500, 1000)

# Virtual machine parameters
VM_SPEED_RANGE = (50, 200)         
VM_MEMORY_RANGE = (4, 16)           
VM_ENERGY_COST_PER_MS = 0.001       
MIGRATION_ENERGY_COST = 0.05        

# Migration parameters
MIGRATION_OVERHEAD_TIME = 50        

# Q-Learning parameters
Q_LEARNING_ALPHA = 0.1
Q_LEARNING_GAMMA = 0.9
Q_LEARNING_EPSILON = 0.2

# ACO parameters
ACO_ALPHA = 1.0
ACO_BETA = 1.0
ACO_EVAPORATION_RATE = 0.1
ACO_PHEROMONE_INIT = 1.0
ACO_PHEROMONE_BOOST = 0.5
